### ISSUE TITLE
question vfd_proc.ko

### ISSUE THREAD

**Issue by dpeddi** [redblue-pkt/buildsystem-vmlinuz-initrd-vuultimo4k#1]
Hello,

I'm trying to get vfd_proc.ko working on a custom build kernel, but I'm unable to get it to work.

(my kernel signature is different from the original one so i've patched the string on the ko)

Does it work with you custom kernel? Could you share the trick to make it working?

**Comment by redblue-pkt** [comment]
You must use the same kernel as in vfd_proc.ko. Not different. I understand that you want to add your improvements. Unfortunately, there are no sources for this module.

**Comment by dpeddi** [comment]
Thank you, my mistake is that i was starting the kernel by kexec or after a cold reboot.
It seems that the vfd_proc.ko module needs that bolt leave the display pre_initializated...
So it works after a fresh flashing  of kernel or initrd (with something already wrote on it), but it doesn't work after a reboot.

Thank you for your support!
